config/routes.rb
Rails.application.routes.draw do
  get 'messages/new'
  post 'messages/create'
  get 'channels/index'
  get 'channels/show'
  get 'channels/new'
  get 'channels/create'
  devise_for :users

  resources :channels, only: [:index, :new, :create, :show]
  root 'channels#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :messages
  validates :name, format: { multiline: true, without: /^(?=\s*$)/ }
end

app/models/message.rb
class Message < ApplicationRecord

  after_create_commit {broadcast_append_to :show_messages, target: self.channel.created_at , partial: 'messages/message', locals: { message: self, self_user: self.user } }


  default_scope { order(created_at: :desc) }
  belongs_to :channel
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :messages
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username,  :email, :password, :password_confirmation])
  end

end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  def index
    @channels = Channel.all
  end

  def show
    @channels = Channel.all
    @channel = Channel.find(params[:id])
    unless turbo_frame_request?
      render "index", channel: @channel
      return
    end
  end

  def new
    @channel = Channel.new
  end

  def create
    @channel = Channel.new(channel_params)
    if @channel.save
      redirect_to channels_index_path
    end
  end

  private

  def channel_params
    params.require(:channel).permit(:name)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    Message.new
  end

  def create
    @message = Message.new(message_params)
    @message.user_id = current_user.id
    unless @message.content.blank?
      @message.save
    else
      flash[:notice] = 'It cant be blank'
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :channel_id, :user_id)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def show
  end
  def create
    raise
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
  end
  def create
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channel_helper.rb
module ChannelHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/channels/_chatroom.html.erb
<%= turbo_frame_tag "chat", class: "my-4 mr-4 p-4 border-[1px] rounded-lg min-w-96 w-[800px] max-w-3xl" do %>
  <% if channel.present? %>
    <h1 class="text-center text-2xl font-semibold"><%= channel.name %></h1>
    <%= render "messages/channel_messages", channel: channel, self_user: current_user %>
  <% end %>
<% end %>

app/views/channels/create.html.erb
<h1>Channel#create</h1>
<p>Find me in app/views/channel/create.html.erb</p>

app/views/channels/index.html.erb
<% id = params[:id] %>
<div class="flex w-screen h-screen">
  <div class="m-4">
    <ul class="menu p-0 mb-2 w-56 border-[1px] rounded-lg">
      <% @channels.each do |channel| %>
        <li><%= link_to channel.name, channels_show_url(id: channel.id), data: {turbo_action: "advance", turbo_frame: "chat"} %></li>
      <% end %>
    </ul>
    <%= link_to "Create new channel", channels_new_path, class: "btn btn-outline btn-sm" %>
  </div>
  <%= turbo_stream_from :show_messages %>
  <% unless id.nil? %>
    <%= render "chatroom", channel: @channels.find(id) %>
  <% end %>
</div>

app/views/channels/new.html.erb
<%= form_with(model: @channel, local: true) do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %>
  <%= f.submit "Create channel" %>
<% end %>

app/views/channels/show.html.erb
<%= render partial: "chatroom", locals: {channel: @channel} %>

app/views/icons/_send.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class="mb-[-17px]" height="48" viewBox="0 -960 960 960" width="48"><path d="M114.5-154.261v-651.478L887.174-480 114.5-154.261ZM180-255.63 717.304-480 180-707.37v162.74L424.63-480 180-417.37v161.74Zm0 0v-451.74 451.74Z"/></svg>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snakkeapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" type="image" href="https://static-00.iconduck.com/assets.00/chat-icon-2048x2048-i7er18st.png">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_channel_messages.html.erb
  <div class="flex flex-col h-[84vh] overflow-auto flex-col-reverse">
    <div id="<%= channel.created_at %>">
    </div>
    <% channel.messages.each do |message| %>
      <%= render "messages/message", message: message, self_user: self_user %>
    <% end %>
  </div>
  <%= form_with model: Message.new, url: messages_create_path, remote: true do |f| %>
    <%= f.hidden_field :channel_id, value: channel.id %>
    <%= f.text_field :content, class: "rounded-md h-8" %>
    <%= button_tag(type: "submit") do %>
      <% render "icons/send" %>
    <% end %>
  <% end %>

app/views/messages/_message.html.erb
<% if message.user == self_user %>
  <div class="chat chat-start flex flex-col mb-2">
    <div class="flex mb-[6px] chat-start">
      <h1 class="chat-header mr-2 text-white"><%= message.user.username %></h1>
      <time class="text-xs text-white"><%= message.created_at.strftime("%H:%M %d. %b") %></time>
    </div>
    <div class="chat-bubble chat-bubble-primary"><%= message.content %></div>
  </div>
<% else %>
  <div class="chat chat-end flex flex-col mb-2">
    <div class="flex mb-[6px] chat-start">
      <time class="text-xs text-white"><%= message.created_at.strftime("%H:%M %d. %b") %></time>
      <h1 class="chat-header mr-2 text-white ml-2"><%= message.user.username %></h1>
    </div>
    <div class="chat-bubble"><%= message.content %></div>
  </div>
<% end %>

app/views/messages/new.html.erb
<h1>Messages#new</h1>
<p>Find me in app/views/messages/new.html.erb</p>